name: C++ Build and Test

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v3 # Checks out your code

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libstb-dev python3 python3-pip 
        pip3 install matplotlib-cpp 

    - name: Check Python version
      run: python --version

    - name: Check pip version
      run: pip --version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build
      working-directory: ./build
      run: 1  cmake --build . --config Release

    - name: Run
      working-directory: ./build
      run: ./main_code.cpp # Replace with your executable name
