name: C++ Build and Test

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v3 # Checks out your code

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libstb-dev python3 python3-pip python3-matplotlib
        
        git clone https://github.com/lava/matplotlib-cpp.git
        cd matplotlib-cpp
        mkdir build
        cd build
        cmake ..
        sudo make install
        cd ../../

    - name: Check Python version
      run: python --version

    - name: Check pip version
      run: pip --version

    - name: Check matplotlib
      run: ls -lR matplotlib-cpp/build

    - name: Configure CMake (matplotlib-cpp)
      working-directory: ./matplotlib-cpp/build
      run: cmake .. 

    - name: Build (matplotlib-cpp)
      working-directory: ./matplotlib-cpp/build
      run: cmake --build .

    - name: Check for matplotlib-cppConfig.cmake
      run: ls -l /home/runner/work/Compression/Compression/matplotlib-cpp/build

    - name: Clean build dir
      run: |
        rm -rf build
        mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: cmake .. 

    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release

    - name: List Files in Build Directory
      working-directory: ./build
      run: ls -lR  # List files recursively

    - name: Run
      working-directory: ./build
      run: ./Compression # Replace with your executable name

    # Add this step to upload artifacts
    - uses: actions/upload-artifact@v3
      with:
          name: Graphs  # Or any name you prefer
          path: ./build/*.png # Assuming your graphs are in the build directory
