name: C++ Build and Test

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v3 # Checks out your code

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libstb-dev python3 python3-pip libasio-dev python3-matplotlib
        git clone https://github.com/lava/matplotlib-cpp.git
        cd matplotlib-cpp
        mkdir build
        cd build
        cmake ..
        sudo make install
        cd ../../

    - name: Check Python version
      run: python --version

    - name: Check pip version
      run: pip --version

    - name: Install Crow
      run: |
        git clone https://github.com/CrowCpp/Crow.git
        cd Crow
        mkdir build
        cd build
        cmake ..
        sudo make install
        cd ../../

    - name: Create build directory
      run: mkdir build

    - name: Print paths
      working-directory: ./build
      run: |
        ASIO_INCLUDE_PATH=$(cmake -E env ASIO_INCLUDE_DIR)
        echo "ASIO include path: $ASIO_INCLUDE_PATH"
        MATPLOTLIB_CPP_INCLUDE_PATH=$(cmake -E enve matplotlib-cpp_INCLUDE_DIRS)
        echo "Matplot include path: $MATPLOTLIB-CPP_INCLUDE_PATH"
        CROW_INCLUDE_PATH=$(cmake -E env Crow_INCLUDE_DIRS)
        echo "Crow include path: $CROW_INCLUDE_PATH"

    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build
      working-directory: ./build
      run: 1  cmake --build . --config Release

    - name: Run
      working-directory: ./build
      run: ./main_code.cpp # Replace with your executable name
